%  This script repackages the simulation results into a common data struct
%  for plotting.

%  --extract signals from VC_data_log for plotting

clear sigs
sigs = {'mode_select', ...
    'action_select', ...
    'wpt_status_change', ...
    'AV_mode_active', ...
    'gear_fbk', ...
    'torque_fbk', ...
    'brake_fbk', ...
    'steer_fbk', ...
    'northr', ...
    'eastr', ...
    'psi', ...
    'vcar', ...
    'alat', ...
    'along', ...
    'pitch', ...
    'VC_state', ...
    'speed_mode', ...
    'steer_mode', ...
    'path_mode', ...
    'AV_start_request', ...
    'wpt_index', ...
    'vref', ...
    'north_target', ...
    'east_target', ...
    'signal_cmd', ...
    'xterr', ...
    'torque_cmd', ...
    'brake_cmd', ...
    'vdes', ...
    'car_is_stopped', ...
    'steer_cmd', ...
    'jlat', ...
    'jlong', ...
    'end_of_data', ...
    'kpdes', ...
    'kdes'};

NS = length(sigs);
for n = 1:NS
    eval(sprintf('sim.%s = VC_data_log(:,%d);',sigs{n},n));
end
NT = length(sim.mode_select);
t = ts * [0:NT-1]';
sim.t = t;


%  --extract signals from forces for plotting

clear sigs
sigs = {'Fgrade','Fsum','Fnet','Fdamp'};
NS = length(sigs);
for n = 1:NS
    eval(sprintf('sim.%s = forces(:,%d);',sigs{n},n));
end


%  --extract signals from pose_cg for plotting

clear sigs
sigs = {'eastcg','northcg','vcg'};
NS = length(sigs);
for n = 1:NS
    eval(sprintf('sim.%s = pose_cg(:,%d);',sigs{n},n));
end

%  --extract waypoint index

wpt_index = sim.wpt_index;


clear sigs NS NT t