classdef validate_sim_results < matlab.unittest.TestCase
    properties
        % Default course name (will be overridden per test)
        courseName = '';
    end

    
    properties(Constant)
        % Map matrix case numbers to course names
        courseList = {...
            'lanechange', ...
            'figure8', ...
            'Zandvoort_clothoid', ...
            'Zandvoort', ...
            'Yuma_clothoid', ...
            'Yuma', ...
            'VIR_clothoid', ...
            'VIR', ...
            'RoadAmerica_clothoid', ...
            'RoadAmerica', ...
            'PikesPeak_clothoid', ...
            'PikesPeak', ...
            'VTTI_VIC'};
    end
    
    methods(Test)
        function validateSimResults(testCase, matrixCase)
            % --- Select course name for this test ---
            testCase.courseName = TestSimValidation.courseList{matrixCase};
            
            % --- Load the simulation file generated by this matrix job ---
            simFile = sprintf('simdata_%02d.mat', matrixCase);
            if ~exist(simFile,'file')
                error('Simulation file %s not found.', simFile);
            end
            S = load(simFile);
            sim = S.sim;
            
            % --- Thresholds ---
            thresholds.max_xterr = 0.25;
            thresholds.max_verr  = 0.50;
            thresholds.max_jerk  = 2.50;
            thresholds.max_alat  = 3.00;
            thresholds.tta_limit = 0.10;
            
            % --- Basic Calculations ---
            v_error = abs(sim.vdes - sim.vcar);
            max_xt_err = max(abs(sim.xterr));
            max_v_err  = max(v_error);
            max_j_long = max(abs(sim.jlat));
            max_a_lat  = max(abs(sim.alat));
            
            % --- Scenario Logic ---
            is_lane_change = max(abs(diff(sim.psi))) > 0.05;
            
            jamming_status = 'N/A';
            jamming_pass = true;
            if any(sim.wpt_status_change==1)
                fault_idx = find(sim.wpt_status_change==1,1);
                reaction_idx = find(sim.VC_state(fault_idx:end)~=4,1)+fault_idx-1;
                if ~isempty(reaction_idx)
                    reaction_time = sim.t(reaction_idx) - sim.t(fault_idx);
                    jamming_pass = reaction_time <= thresholds.tta_limit;
                    jamming_status = sprintf('%.3fs', reaction_time);
                else
                    jamming_pass = false;
                    jamming_status = 'NO REACTION';
                end
            end
            
            % --- Evaluate Metrics ---
            metrics = {
                'Cross Track Error', max_xt_err, thresholds.max_xterr, max_xt_err<=thresholds.max_xterr;
                'Velocity Tracking', max_v_err, thresholds.max_verr, max_v_err<=thresholds.max_verr;
                'Longitudinal Jerk', max_j_long, thresholds.max_jerk, max_j_long<=thresholds.max_jerk;
                'Lateral Accel', max_a_lat, thresholds.max_alat, max_a_lat<=thresholds.max_alat;
            };
            
            if is_lane_change
                metrics(end+1,:) = {'Lane Change Stability', max_a_lat, thresholds.max_alat, max_a_lat<=thresholds.max_alat};
            end
            if ~strcmp(jamming_status,'N/A')
                metrics(end+1,:) = {'Jamming TTA', reaction_time, thresholds.tta_limit, jamming_pass};
            end
            
            % --- Display ---
            fprintf('\n--- VALIDATION REPORT: %s ---\n', testCase.courseName);
            fprintf('%-25s | %-10s | %-10s | %-8s\n','Metric','Value','Limit','Status');
            fprintf('%s\n', repmat('-',1,65));
            for i=1:size(metrics,1)
                status='FAIL';
                if metrics{i,4}, status='PASS'; end
                fprintf('%-25s | %-10.3f | %-10.3f | %-8s\n', metrics{i,1},metrics{i,2},metrics{i,3},status);
            end
            
            % --- Assert ---
            testCase.verifyTrue(all(cell2mat(metrics(:,4))), 'One or more metrics failed validation.');
        end
    end
end
